ci: edit tagname3

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -30,10 +30,6 @@ jobs:
           images: hermeserm/polyvault
           tags: type=sha,prefix=
 
-      - name: Fail if no tags were generated
-        run: |
-          [ -n "${{ steps.meta.outputs.tags }}" ] || { echo "::error::no tags generated"; exit 1; }
-
       - name: Build and push Docker image
         id: push
         uses: docker/build-push-action@v7
@@ -41,5 +37,9 @@ jobs:
           context: . # Defines the build's context as the set of files located in the specified path
           file: ./Dockerfile
           push: true
-          tags: hermeserm/polyvault:${{ steps.meta.outputs.DOCKER_METADATA_OUTPUT_TAG_NAMES }}
+          tags: hermeserm/polyvault:latest
           labels: ${{ steps.meta.outputs.labels }}
+
+      - name: Fail if no tags were generated
+        run: |
+          [ -n "${{ steps.meta.outputs.tags }}" ] || { echo "::error::no tags generated"; exit 1; }
